// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfmD5h8iMvTRpFCD6WezkVndJq1mgUyI',
    appId: '1:80219659535:web:d3b7ba380e19dee9c5727a',
    messagingSenderId: '80219659535',
    projectId: 'lab9-b2cde',
    authDomain: 'lab9-b2cde.firebaseapp.com',
    storageBucket: 'lab9-b2cde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NZaTYMSmj1KkbxL7EY7kG5UffVqDFgo',
    appId: '1:80219659535:android:d278b62a51349c00c5727a',
    messagingSenderId: '80219659535',
    projectId: 'lab9-b2cde',
    storageBucket: 'lab9-b2cde.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzfmD5h8iMvTRpFCD6WezkVndJq1mgUyI',
    appId: '1:80219659535:web:76332da929bf74bec5727a',
    messagingSenderId: '80219659535',
    projectId: 'lab9-b2cde',
    authDomain: 'lab9-b2cde.firebaseapp.com',
    storageBucket: 'lab9-b2cde.firebasestorage.app',
  );
}
